service: endpoint-circle

provider:
  name: aws
  runtime: nodejs10.x

functions:
  createCircle:
    handler: handler.createCircle
    events:
      - http:
          path: circle
          method: post
          integration: lambda-proxy
