service: endpoint-circle

provider:
  name: aws
  runtime: nodejs10.x
  layers:
    - arn:aws:lambda:us-east-1:520205089606:layer:nomopore-common:7

package:
  exclude:
    - node_modules/@matheuspiment/**

functions:
  createCircle:
    handler: handler.createCircle
    events:
      - http:
          path: circle
          method: post
          integration: lambda-proxy
